POST http://localhost:8080/api/board
Content-Type: application/json

{
  "writer_id": 1,
  "title": "제목이다.",
  "content": "내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다."
}