PUT http://localhost:8080/board/editForm/1
Content-Type: application/json

{
  "title": "수정된 제목이다.",
  "content": "수정된 내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다.내용입니다."
}